using System;
using System.Collections.Generic;
using System.Linq;

namespace DevExtreme.NETCore.Demos.Models.SampleData {
    public partial class SampleData {
        public static readonly IEnumerable<string> Cities = new[] {
            "Albuquerque",
            "Anaheim",
            "Anchorage",
            "Arlington",
            "Atlanta",
            "Aurora",
            "Austin",
            "Bakersfield",
            "Baltimore",
            "Baton Rouge",
            "Boise",
            "Boston",
            "Buffalo",
            "Chandler",
            "Charlotte",
            "Chesapeake",
            "Chicago",
            "Chula Vista",
            "Cincinnati",
            "Cleveland",
            "Colorado Springs",
            "Columbus",
            "Corpus Christi",
            "Dallas",
            "Denver",
            "Detroit",
            "Durham",
            "El Paso",
            "Fort Wayne",
            "Fort Worth",
            "Fremont",
            "Fresno",
            "Garland",
            "Gilbert",
            "Glendale",
            "Greensboro",
            "Henderson",
            "Hialeah",
            "Honolulu",
            "Houston",
            "Indianapolis",
            "Irvine",
            "Irving",
            "Jacksonville",
            "Jersey City",
            "Kansas City",
            "Laredo",
            "Las Vegas",
            "Lexington",
            "Lincoln",
            "Long Beach",
            "Los Angeles",
            "Louisville",
            "Lubbock",
            "Madison",
            "Memphis",
            "Mesa",
            "Miami",
            "Milwaukee",
            "Minneapolis",
            "Nashville",
            "New Orleans",
            "New York",
            "Newark",
            "Norfolk",
            "North Las Vegas",
            "Oakland",
            "Oklahoma City",
            "Omaha",
            "Orlando",
            "Philadelphia",
            "Phoenix",
            "Pittsburgh",
            "Plano",
            "Portland",
            "Raleigh",
            "Reno",
            "Richmond",
            "Riverside",
            "Sacramento",
            "Saint Paul",
            "San Antonio",
            "San Diego",
            "San Francisco",
            "San Jose",
            "Santa Ana",
            "Scottsdale",
            "Seattle",
            "St. Louis",
            "St. Petersburg",
            "Stockton",
            "Tampa",
            "Toledo",
            "Tucson",
            "Tulsa",
            "Virginia Beach",
            "Washington",
            "Wichita",
            "Winston–Salem"
        };
    }
}
