using System;
using System.Collections.Generic;

namespace DevExtreme.NETCore.Demos.Models.SampleData {
    public partial class SampleData {
        public static readonly IEnumerable<CustomEditorsEmployee> CustomEditorsEmployees = new[] {
            new CustomEditorsEmployee {
                ID = 1,
                FullName = "John Heart",
                Department = "Management",
                Title = "CEO",
            },
            new CustomEditorsEmployee {
                ID = 2,
                FullName = "Samantha Bright",
                Department = "Management",
                Title = "COO",
            },
            new CustomEditorsEmployee {
                ID = 3,
                FullName = "Arthur Miller",
                Department = "Management",
                Title = "CTO",
            },
            new CustomEditorsEmployee {
                ID = 4,
                FullName = "Robert Reagan",
                Department = "Management",
                Title = "CMO",
            },
            new CustomEditorsEmployee {
                ID = 5,
                FullName = "Greta Sims",
                Department = "Human Resources",
                Title = "HR Manager",
            },
            new CustomEditorsEmployee {
                ID = 6,
                FullName = "Brett Wade",
                Department = "IT",
                Title = "IT Manager",
            },
            new CustomEditorsEmployee {
                ID = 7,
                FullName = "Sandra Johnson",
                Department = "Human Resources",
                Title = "Controller",
            },
            new CustomEditorsEmployee {
                ID = 8,
                FullName = "Ed Holmes",
                Department = "Sales",
                Title = "Sales Manager",
            },
            new CustomEditorsEmployee {
                ID = 9,
                FullName = "Barb Banks",
                Department = "Support",
                Title = "Support Manager",
            },
            new CustomEditorsEmployee {
                ID = 10,
                FullName = "Kevin Carter",
                Department = "Shipping",
                Title = "Shipping Manager",
            },
            new CustomEditorsEmployee {
                ID = 11,
                FullName = "Cindy Stanwick",
                Department = "Human Resources",
                Title = "HR Assistant",
            },
            new CustomEditorsEmployee {
                ID = 12,
                FullName = "Sammy Hill",
                Department = "Sales",
                Title = "Sales Assistant",
            },
            new CustomEditorsEmployee {
                ID = 13,
                FullName = "Davey Jones",
                Department = "Shipping",
                Title = "Shipping Assistant",
            },
            new CustomEditorsEmployee {
                ID = 14,
                FullName = "Victor Norris",
                Department = "Shipping",
                Title = "Shipping Assistant",
            },
            new CustomEditorsEmployee {
                ID = 15,
                FullName = "Mary Stern",
                Department = "Shipping",
                Title = "Shipping Assistant",
            },
            new CustomEditorsEmployee {
                ID = 16,
                FullName = "Robin Cosworth",
                Department = "Shipping",
                Title = "Shipping Assistant",
            },
            new CustomEditorsEmployee {
                ID = 17,
                FullName = "Kelly Rodriguez",
                Department = "Support",
                Title = "Support Assistant",
            },
            new CustomEditorsEmployee {
                ID = 18,
                FullName = "James Anderson",
                Department = "Support",
                Title = "Support Assistant",
            },
            new CustomEditorsEmployee {
                ID = 19,
                FullName = "Antony Remmen",
                Department = "Support",
                Title = "Support Assistant",
            },
            new CustomEditorsEmployee {
                ID = 20,
                FullName = "Olivia Peyton",
                Department = "Sales",
                Title = "Sales Assistant",
            },
            new CustomEditorsEmployee {
                ID = 21,
                FullName = "Taylor Riley",
                Department = "IT",
                Title = "Network Admin",
            },
            new CustomEditorsEmployee {
                ID = 22,
                FullName = "Amelia Harper",
                Department = "IT",
                Title = "Network Admin",
            },
            new CustomEditorsEmployee {
                ID = 23,
                FullName = "Wally Hobbs",
                Department = "IT",
                Title = "Programmer",
            },
            new CustomEditorsEmployee {
                ID = 24,
                FullName = "Brad Jameson",
                Department = "IT",
                Title = "Programmer",
            },
            new CustomEditorsEmployee {
                ID = 25,
                FullName = "Karen Goodson",
                Department = "IT",
                Title = "Programmer",
            },
            new CustomEditorsEmployee {
                ID = 26,
                FullName = "Marcus Orbison",
                Department = "Human Resources",
                Title = "Travel Coordinator",
            },
            new CustomEditorsEmployee {
                ID = 27,
                FullName = "Sandy Bright",
                Department = "Human Resources",
                Title = "Benefits Coordinator",
            },
            new CustomEditorsEmployee {
                ID = 28,
                FullName = "Morgan Kennedy",
                Department = "IT",
                Title = "Graphic Designer",
            },
            new CustomEditorsEmployee {
                ID = 29,
                FullName = "Violet Bailey",
                Department = "IT",
                Title = "Jr Graphic Designer",
            },
            new CustomEditorsEmployee {
                ID = 30,
                FullName = "Ken Samuelson",
                Department = "Human Resources",
                Title = "Ombudsman",
            },
            new CustomEditorsEmployee {
                ID = 31,
                FullName = "Nat Maguiree",
                Department = "Support",
                Title = "Trainer",
            },
            new CustomEditorsEmployee {
                ID = 32,
                FullName = "Bart Arnaz",
                Department = "Engineering",
                Title = "Director of Engineering",
            },
            new CustomEditorsEmployee {
                ID = 33,
                FullName = "Leah Simpson",
                Department = "Engineering",
                Title = "Test Coordinator",
            },
            new CustomEditorsEmployee {
                ID = 34,
                FullName = "Arnie Schwartz",
                Department = "Engineering",
                Title = "Engineer",
            },
            new CustomEditorsEmployee {
                ID = 35,
                FullName = "Billy Zimmer",
                Department = "Engineering",
                Title = "Engineer",
            },
            new CustomEditorsEmployee {
                ID = 36,
                FullName = "Samantha Piper",
                Department = "Engineering",
                Title = "Engineer",
            },
            new CustomEditorsEmployee {
                ID = 37,
                FullName = "Maggie Boxter",
                Department = "Engineering",
                Title = "Engineer",
            },
            new CustomEditorsEmployee {
                ID = 38,
                FullName = "Terry Bradley",
                Department = "Engineering",
                Title = "QA Engineer",
            },
            new CustomEditorsEmployee {
                ID = 39,
                FullName = "Gabe Jones",
                Department = "Support",
                Title = "Retail Coordinator",
            },
            new CustomEditorsEmployee {
                ID = 40,
                FullName = "Lucy Ball",
                Department = "Sales",
                Title = "Sales Assistant",
            },
            new CustomEditorsEmployee {
                ID = 41,
                FullName = "Jim Packard",
                Department = "Sales",
                Title = "Retail Sales Manager",
            },
            new CustomEditorsEmployee {
                ID = 42,
                FullName = "Hannah Brookly",
                Department = "Sales",
                Title = "Online Sales Manager",
            },
            new CustomEditorsEmployee {
                ID = 43,
                FullName = "Harv Mudd",
                Department = "Sales",
                Title = "Retail Sales Manager",
            },
            new CustomEditorsEmployee {
                ID = 44,
                FullName = "Clark Morgan",
                Department = "Sales",
                Title = "Retail Sales Manager",
            },
            new CustomEditorsEmployee {
                ID = 45,
                FullName = "Todd Hoffman",
                Department = "Sales",
                Title = "Retail Sales Manager",
            },
            new CustomEditorsEmployee {
                ID = 46,
                FullName = "Jackie Garmin",
                Department = "Support",
                Title = "Support Assistant",
            },
            new CustomEditorsEmployee {
                ID = 47,
                FullName = "Lincoln Bartlett",
                Department = "Sales",
                Title = "Sales Assistant",
            },
            new CustomEditorsEmployee {
                ID = 48,
                FullName = "Brad Farkus",
                Department = "Engineering",
                Title = "Engineer",
            },
            new CustomEditorsEmployee {
                ID = 49,
                FullName = "Jenny Hobbs",
                Department = "Shipping",
                Title = "Shipping Assistant",
            },
            new CustomEditorsEmployee {
                ID = 50,
                FullName = "Dallas Lou",
                Department = "Shipping",
                Title = "Shipping Assistant",
            },
            new CustomEditorsEmployee {
                ID = 51,
                FullName = "Stu Pizaro",
                Department = "Engineering",
                Title = "Engineer",
            }
        };
    }
}
