name: Get changed files
description: Get changed files

runs:
  using: composite
  steps:
    - name: Get changed files
      shell: bash
      run: |
        gh api \
          -H "Accept: application/vnd.github+json" \
          "/repos/{owner}/{repo}/pulls/${{github.event.pull_request.number}}/files" --paginate \
          --jq '.[] | {filename:.filename}' | jq -s > changed-files.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

