name: 'Get changed files'
description: 'Get list of the pull request files and save it to file system as a JSON file'

inputs:
  path:
    description: 'Path to file'
    required: true

runs:
  using: composite
  steps:
    - name: Get changed files
      shell: bash
      run: |
        gh api \
          -H "Accept: application/vnd.github+json" \
          "/repos/{owner}/{repo}/pulls/${{github.event.pull_request.number}}/files" --paginate \
          --jq '.[] | {filename:.filename}' | jq -s > {{ inputs.path }}
