name: Lint

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "[0-9][0-9]_[0-9]"

jobs:
  package_lock:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Check package-lock
      run: |
        node -v
        npm -v
        npm install --no-audit --no-fund --ignore-scripts
        git diff --exit-code package-lock.json

  build:
    runs-on: ubuntu-latest
    name: Build DevExtreme
    timeout-minutes: 30

    steps:

    #Git
    - name: Get sources
      uses: actions/checkout@v3

    - name: Clone devextreme repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: git clone -b ${{github.event.pull_request.head.ref}} https://github.com/${{github.event.pull_request.user.login}}/devextreme ./devextreme-repo

    - name: Clone devextreme repo
      run: |
        BASE_BRANCH=$(node -p -e "require('./package.json').version.slice(0, 4).replace('.', '_')")
        test -d ./devextreme-repo || git clone -b $BASE_BRANCH https://github.com/devexpress/devextreme ./devextreme-repo

    #Build Devextreme
    - name: DevExtreme - Restore npm cache
      uses: actions/cache@v3
      with:
        path: 'devextreme-repo/**/node_modules'
        key: ${{ runner.os }}-devextreme-node-modules-${{ hashFiles('devextreme-repo/**/package-lock.json') }}

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'

    - name: DevExtreme - Install packages
      working-directory: ./devextreme-repo
      run: npm install --no-audit --no-fund

    - name: DevExtreme - Build
      working-directory: ./devextreme-repo/packages/devextreme
      run: npm run build-npm-devextreme

    - name: DevExtreme - Pack
      working-directory: ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme
      run: npm pack

    - name: DevExtreme dist - Pack
      working-directory: ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme-dist
      run: npm pack

    #Build Demos
    - name: Demos - Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Delete DX packages
      run:  sed -i '/23.2-next/d' ./package.json

    - name: Demos - Install packages
      run: |
        npm install --no-audit --no-fund

    - name: Demos - Install devextreme package
      run: npm install $(find ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme/ -maxdepth 1 -name "devextreme-*.tgz")

    - name: Demos - Install devextreme-dist package
      run: npm install $(find ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme-dist/ -maxdepth 1 -name "devextreme-*.tgz")

    #Publish artifacts
    - name: Zip node_modules
      run: 7z a -t7z -mx3 -mmt2 node_modules.7z node_modules

    - name: Copy build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: devextreme-sources
        path: node_modules.7z
        retention-days: 1

  lint:
    name: ${{ matrix.name }}
    needs:
      - build-demos

    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint code base (excluding demos)
            command: npm run lint-non-demos
          - name: Lint demos (1/4)
            command: CONSTEL=1/4 npm run lint-demos
          - name: Lint demos (2/4)
            command: CONSTEL=2/4 npm run lint-demos
          - name: Lint demos (3/4)
            command: CONSTEL=3/4 npm run lint-demos
          - name: Lint demos (4/4)
            command: CONSTEL=4/4 npm run lint-demos

  check_generated_demos:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Check generated demos (1/4)
            command: CONSTEL=1/4 npm run convert-to-js
          - name: Check generated demos (2/4)
            command: CONSTEL=2/4 npm run convert-to-js
          - name: Check generated demos (3/4)
            command: CONSTEL=3/4 npm run convert-to-js
          - name: Check generated demos (4/4)
            command: CONSTEL=4/4 npm run convert-to-js
    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules
    
    - name: Delete DX packages
      run:  sed -i '/23.2-next/d' ./package.json

    - name: Download devextreme sources
      uses: actions/download-artifact@v3
      with:
        name: devextreme-sources

    - name: Unpack artifacts
      run: 7z x node_modules.7z

    - name: Check generated JS demos
      run: |
        npm install --no-audit --no-fund --ignore-scripts
        
        git reset --hard

        ${{ matrix.command }}

        git add ./JSDemos/Demos -N

        if git diff --exit-code ; then
          echo "Generated JS demos are up-to-date"
        else
            echo "Generated JS demos are outdated. Execute 'npm run convert-to-js ./JSDemos/Demos/**/React' and commit changes."
            echo "If you see another diff, ensure that extra listed files have LF endings."
            exit 1
        fi


