name: Lint

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "[0-9][0-9]_[0-9]"

jobs:
  package_lock:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Check package-lock
      run: |
        node -v
        npm -v
        npm install --no-audit --no-fund --ignore-scripts
        git diff --exit-code package-lock.json
