name: Publish Demos to GH Pages

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read version from package.json and append "-stable"
        run: echo echo "STABLE_VERSION=$(jq -r '.version' package.json | awk -F. '{print $1 "." $2}')-stable" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Install stable devextreme pacakges
        run: npm install devextreme@${{ env.STABLE_VERSION }} devextreme-angular@${{ env.STABLE_VERSION }} devextreme-react@${{ env.STABLE_VERSION }} devextreme-vue@${{ env.STABLE_VERSION }}

      - name: Copy metadata
        run: npm run make-demos-bundle -- --copy-metadata

      - name: Prepare React demo bundles
        run: npm run make-demos-bundle -- --framework React

      - name: Prepare Vue demo bundles
        run: npm run make-demos-bundle -- --framework Vue

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish-demos
