name: Publish Demos to GH Pages

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
      
      - name: Copy metadata
        run: npm run make-demos-bundle -- --copy-metadata

      - name: Prepare React demo bundles
        run: npm run make-demos-bundle -- --framework React

      - name: Prepare Vue demo bundles
        run: npm run make-demos-bundle -- --framework Vue

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish-demos
