name: Unit tests

on: [push, pull_request]

jobs:
  test:
    name: Run unit tests

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Get sources
        uses: actions/checkout@v2

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Run npm install
        run: npm install --no-audit --no-fund

      - name: Run unit tests
        run: npm run test
