name: Unit tests

on: [push, pull_request]

jobs:
  test:
    name: Run unit tests

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Get sources
        uses: actions/checkout@v2

      - name: Run npm install
        run: npm install --no-package-lock --no-audit --no-fund

      - name: Run unit tests
        run: npm run test
