name: Visual Tests

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "[0-9][0-9]_[0-9]"
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 6,0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build DevExtreme
    timeout-minutes: 15

    steps:

    #Git
    - name: Get sources
      uses: actions/checkout@v3

    - name: Clone devextreme repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: git clone -b ${{github.event.pull_request.head.ref}} https://github.com/${{github.event.pull_request.user.login}}/devextreme ./devextreme-repo

    - name: Clone devextreme repo
      run: |
        BASE_BRANCH=$(node -p -e "require('./package.json').version.slice(0, 4).replace('.', '_')")
        test -d ./devextreme-repo || git clone -b $BASE_BRANCH https://github.com/devexpress/devextreme ./devextreme-repo

    #Build Devextreme
    - name: DevExtreme - Restore npm cache
      uses: actions/cache@v3
      with:
        path: 'devextreme-repo/**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('devextreme-repo/**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: DevExtreme - Install packages
      working-directory: ./devextreme-repo
      run: npm install --no-audit --no-fund

    - name: DevExtreme - Build
      working-directory: ./devextreme-repo/packages/devextreme
      run: npm run build-npm-devextreme

    - name: DevExtreme - Pack
      working-directory: ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme
      run: npm pack

    - name: DevExtreme dist - Pack
      working-directory: ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme-dist
      run: npm pack

    #Build Demos
    - name: Demos - Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Delete DX packages
      run:  sed -i '/23.2-next/d' ./package.json

    - name: Demos - Install packages
      run: |
        npm install --no-audit --no-fund

    - name: Demos - Install devextreme package
      run: npm install $(find ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme/ -maxdepth 1 -name "devextreme-*.tgz")

    - name: Demos - Install devextreme-dist package
      run: npm install $(find ./devextreme-repo/packages/devextreme/artifacts/npm/devextreme-dist/ -maxdepth 1 -name "devextreme-*.tgz")

    #Publish artifacts
    - name: Zip node_modules
      run: 7z a -t7z -mx3 -mmt2 node_modules.7z node_modules

    - name: Copy build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: devextreme-sources
        path: node_modules.7z
        retention-days: 1

  testcafe:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        STRATEGY: [screenshots, accessibility]
        CONSTEL: [jquery(1/4), jquery(2/4), jquery(3/4), jquery(4/4)]
    env:
      ACCESSIBILITY_TESTCAFE_REPORT_PATH: "accessibility_testcafe_report"

    runs-on: ubuntu-latest
    name: ${{ matrix.CONSTEL }}-${{ matrix.STRATEGY }}
    timeout-minutes: 20

    steps:
#    - name: Pin Chrome version
#      run: |
#        CHROME_VERSION=103.0.5060.134-1
#        wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb"
#        sudo dpkg -i "google-chrome-stable_${CHROME_VERSION}_amd64.deb"

    - name: Get sources
      uses: actions/checkout@v3

    - name: Delete DX packages
      run:  sed -i '/23.2-next/d' ./package.json

    - name: Download devextreme sources
      uses: actions/download-artifact@v3
      with:
        name: devextreme-sources

    - name: Unpack artifacts
      run: 7z x node_modules.7z

    - name: Prepare JS
      run: npm run prepare-js

    - name: Run Web Server
      run: |
        python -m http.server 8080 &
        python -m http.server 8081 &
        python -m http.server 8082 &
        python -m http.server 8083 &

    - name: Get changed files
      uses: ./.github/actions/get-changed-files
      if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'force all tests')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: changed-files.json

    - name: Run TestCafe tests
      shell: bash
      continue-on-error: ${{ matrix.STRATEGY == 'accessibility' }}
      env:
        STRATEGY: ${{ matrix.STRATEGY }}
        CHANGEDFILEINFOSPATH: ${{ github.workspace }}/changed-files.json
        BROWSERS: chrome:headless --disable-partial-raster --disable-skia-runtime-opts --run-all-compositor-stages-before-draw --disable-new-content-rendering-timeout --disable-threaded-animation --disable-threaded-scrolling --disable-checker-imaging --disable-image-animation-resync --use-gl="swiftshader" --disable-features=PaintHolding --js-flags=--random-seed=2147483647 --font-render-hinting=none --disable-font-subpixel-positioning
        #DEBUG: hammerhead:*,testcafe:*
        CONCURRENCY: 4
        TCQUARANTINE: true
        CONSTEL: ${{ matrix.CONSTEL }}
        # DISABLE_DEMO_TEST_SETTINGS: all # Uncomment to ignore all the visualtestrc.json settings
        # DISABLE_DEMO_TEST_SETTINGS: ignore # Uncomment to ignore the `ignore` field
        # DISABLE_DEMO_TEST_SETTINGS: comparison-options # Uncomment to ignore the `comparison-options` field
        CI_ENV: true # The `ignore` field in the visualtestrc.json should be disabled when running test locally
      run: npm run test-testcafe

    - name: Show accessibility warnings
      if: matrix.STRATEGY == 'accessibility'
      run: |
        message=$(cat $ACCESSIBILITY_TESTCAFE_REPORT_PATH)
        echo "::warning ::$message"

    - name: Copy screenshots artifacts
      if: failure() && matrix.STRATEGY == 'screenshots'
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: ${{ github.workspace }}/testing/artifacts/compared-screenshots/*
        if-no-files-found: ignore

    - name: Copy accessibility report
      if: matrix.STRATEGY == 'accessibility'
      uses: actions/upload-artifact@v3
      with:
        name: accessibility-reports
        path: ${{ github.workspace }}/testing/artifacts/axe-reports/*
        if-no-files-found: ignore
