name: Visual Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 6,0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build DevExtreme
    timeout-minutes: 15
    
    steps:

    #Git
    - name: Get sources
      uses: actions/checkout@v2   

    - name: Clone devextreme repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: git clone -b ${{github.event.pull_request.head.ref}} https://github.com/${{github.event.pull_request.user.login}}/devextreme ../devextreme-repo

    - name: Clone devextreme repo
      run: |
        BASE_BRANCH=$(node -p -e "require('./package.json').version.slice(0, 4).replace('.', '_')")
        test -d ../devextreme-repo || git clone -b $BASE_BRANCH https://github.com/devexpress/devextreme ../devextreme-repo

    #Build Devextreme
    - name: DevExtreme - Generate package-lock
      run: |
        cd ../devextreme-repo
        test -f package-lock.json || npm i --package-lock-only

    - name: DevExtreme - Install packages
      run: |
        cd ../devextreme-repo
        npm ci --no-audit --no-fund

    - name: DevExtreme - Build
      run: |
        cd ../devextreme-repo
        npm run build

    - name: DevExtreme - Pack
      run: |
        cd ../devextreme-repo/artifacts/npm/devextreme
        npm pack

    #Build Demos
    - name: Demos - Generate package-lock
      run: |
        test -f package-lock.json || npm i --package-lock-only

    - name: Demos - Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node

    - name: Demos - Install packages
      run: |
        test -d node_modules || npm ci --no-audit --no-fund

    - name: Demos - Install devextreme package
      run: |
        rm -rf ./node_modules/devextreme
        npm install --no-package-lock $(find ../devextreme-repo/artifacts/npm/devextreme/ -maxdepth 1 -name "devextreme-*.tgz")

    #Publish artifacts
    - name: Zip node_modules    
      run: 7z a -t7z -mx3 -mmt2 node_modules.7z node_modules

    - name: Copy build artifacts      
      uses: actions/upload-artifact@v2
      with:
        name: devextreme-sources        
        path: node_modules.7z
        retention-days: 1

    #Teardown
    - name: Cleanup devextreme package
      run: rm -rf ./node_modules/devextreme
    
  testcafe:
    needs: build
    strategy:
      fail-fast: false
      matrix:      
        CONSTEL: [jquery(1/4), jquery(2/4), jquery(3/4), jquery(4/4)]

    runs-on: ubuntu-latest
    name: ${{ matrix.CONSTEL }}
    timeout-minutes: 10

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Download devextreme sources
      uses: actions/download-artifact@v2
      with:
        name: devextreme-sources

    - name: Unpack artifacts
      run: 7z x node_modules.7z

    - name: Prepare JS
      run: npm run prepare-js

    - name: Run Web Server
      run: |
        python -m http.server 8080 &
        python -m http.server 8081 &
        python -m http.server 8082 &
        python -m http.server 8083 &

    - name: Run TestCafe tests
      env:
        BROWSERS: chrome:headless
        #DEBUG: hammerhead:*,testcafe:*
        CONCURRENCY: 4
        TCQUARANTINE: true
        CONSTEL: ${{ matrix.CONSTEL }}
      run: npm run test-testcafe

    - name: Copy screenshots artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ${{ github.workspace }}/testing/artifacts/*
        if-no-files-found: ignore

  cleanup:
    needs: testcafe
    runs-on: ubuntu-latest
    name: Cleanup artifacts
    timeout-minutes: 10
    steps:
    - name: Prepare delete artifact
      run: touch devextreme-repo-artifacts.tar

    - name: Cleanup artifact      
      uses: actions/upload-artifact@v2
      with:
        name: devextreme-sources
        path: devextreme-repo-artifacts.tar
        retention-days: 1
